baseURL = "https://cpbotha.net/"
languageCode = "en-us"
title = "voices in my head"
theme = ["hugo-theme-minos-cpbotha", "hugo-theme-minos"]
rssLimit = 10
# we only need this for minos to get disqus going.
#disqusShortname = "cpbotha"

#pygmentsCodeFences = true
#pygmentsStyle = "solarized-light"
#pygmentsOptions = "linenos=table"

resourceDir = "/tmp/hugo-resources-cpbotha.net/"

# see https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    # in my note-taking post, we go all the way down to 5!
    endLevel = 5
    ordered = false
    # default is 2, but set to 1 until we've converted all posts to start at 2
    # 1 was the default before goldmark (i.e. with blackdown)
    startLevel = 1
  [markup.highlight]
    style = 'github'

# we need email and name for this to appear in the standard RSS feed
# however, in https://gohugo.io/variables/site/#example-siteparams I see both Site.author AND
# Site.Params.author
[author]
  email = "cpbotha@cpbotha.net"
  name = "Charl P. Botha"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
